### ISSUE TITLE
Recipes not updated after tab refresh

### ISSUE THREAD

**Issue by OchseGit** [Stickymaddness/Procurement#567] opened 2016-03-26 16:17 UTC
The list of recipes is not updated after a tab refresh.

**Comment by Stickymaddness** [comment] 2016-03-27 11:01
I'll take a look into this.

**Comment by Stickymaddness** [comment] 2017-12-17 23:43
This should be fixed now

**Closed by Stickymaddness** 2017-12-17 23:43 UTC

**Comment by robertsmieja** [comment] 2017-12-29 09:53
Is there any estimate for when a new release with this fix will be available?

**Comment by aydjay** [comment] 2017-12-29 11:48
Looks like 1.20 will have your fix. Please let us know if this is not working as intended.
