### ISSUE TITLE
Not able to log in

### ISSUE THREAD

**Issue by Simadra** [Stickymaddness/Procurement#1154] opened 2023-04-19 03:58 UTC
Using my alias with trying both account name and numbers did not work to log in. Session ID used from shop page and also tried from normal page for my account. Tried a lot of different combinations to log in. Sometimes loaded like 27 stash tabs with [OK] sign and then just getting error.

By the use of the log in details which should be correct I'm sending the debug log file.
[DebugInfo.log](https://github.com/Procurement-PoE/Procurement/files/11268360/DebugInfo.log)

**Comment by ghost** [comment] 2023-08-06 04:38
**You must use a valid, up-to-date browser to login. CEF isn't that.**

**Comment by thailyn** [comment] 2023-12-06 04:14
I'm going to close this as a duplicate of #1158 (yeah, I know, this is older, but I saw that one first), as I see a bunch of "Too Many Requests" errors in your log and not much else. If you're still having issues after that bug is resolved, please file a new bug. Thanks!

**Closed as not planned by thailyn** 2023-12-06 04:14 UTC
Labels: bug, duplicate
