### ISSUE TITLE
Error reading character data for _DianWei_ , stash is ok

### ISSUE THREAD

**Issue by evilight** [Stickymaddness/Procurement#720] opened 2017-08-14 15:00 UTC
[Error] Error reading character data for _DianWei_, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.

Debug.log

[14-08-2017 22:59] Error reading character data for character '_DianWei_', Exception info: 
[14-08-2017 22:59] System.Exception: Error reading character data for _DianWei_, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
   POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
   Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
   Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
   System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   System.Threading.Tasks.Task.Execute()

**Comment by driz** [comment] 2017-08-27 03:32
duplicate of [](https://github.com/Stickymaddness/Procurement/issues/725)

Steam User using session id. debug.log below

> [26-08-2017 22:30] Error reading character data for character 'Arieshoots', Exception info: 
> [26-08-2017 22:30] System.Exception: Error reading character data for Arieshoots, if you are in offline mode you will need to login and update. If you received this error while logging in, the authenticated session may have expired or bad data has been returned by GGG or a network issue may have occurred - Please try again.
>    at POEApi.Model.POEModel.GetInventory(String characterName, Boolean forceRefresh, String accountName)
>    at Procurement.ViewModel.LoginWindowViewModel.LoadCharacterInventoryItems(Character character, Boolean offline)
>    at Procurement.ViewModel.LoginWindowViewModel.<LoadItems>d__24.MoveNext()
>    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
>    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
>    at Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
>    at System.Threading.Tasks.Task.Execute()

**Comment by Stickymaddness** [comment] 2017-12-17 23:38
Please update to [Procurement 1.19.0](https://github.com/Stickymaddness/Procurement/releases/tag/1.19.0), and create a new ticket if this is still an issue.

**Closed by Stickymaddness** 2017-12-17 23:38 UTC
