### ISSUE TITLE
error downloading account name

### ISSUE THREAD

**Issue by econcert** [Stickymaddness/Procurement#1085] opened 2020-01-10 09:33 UTC
[10-01-2020 6:16] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (503) Servidor Não Disponível.
[10-01-2020 6:16] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name?realm=pc', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (401) Não Autorizado.
[10-01-2020 6:16] Error downloading account name, exception details: System.Net.WebException: O servidor remoto retornou um erro: (401) Não Autorizado.
   em System.Net.HttpWebRequest.GetResponse()
   em POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.GetAccountName(String realm)
   em POEApi.Model.POEModel.GetAccountName(String realm)
[10-01-2020 6:16] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   em POEApi.Model.POEModel.GetAccountName(String realm)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   em System.Threading.Tasks.Task.Execute()
[10-01-2020 6:16] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (503) Servidor Não Disponível.
[10-01-2020 6:16] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name?realm=pc', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (401) Não Autorizado.
[10-01-2020 6:16] Error downloading account name, exception details: System.Net.WebException: O servidor remoto retornou um erro: (401) Não Autorizado.
   em System.Net.HttpWebRequest.GetResponse()
   em POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.GetAccountName(String realm)
   em POEApi.Model.POEModel.GetAccountName(String realm)
[10-01-2020 6:16] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   em POEApi.Model.POEModel.GetAccountName(String realm)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   em System.Threading.Tasks.Task.Execute()
[10-01-2020 6:23] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (503) Servidor Não Disponível.
[10-01-2020 6:23] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name?realm=pc', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (401) Não Autorizado.
[10-01-2020 6:23] Error downloading account name, exception details: System.Net.WebException: O servidor remoto retornou um erro: (401) Não Autorizado.
   em System.Net.HttpWebRequest.GetResponse()
   em POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.GetAccountName(String realm)
   em POEApi.Model.POEModel.GetAccountName(String realm)
[10-01-2020 6:23] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   em POEApi.Model.POEModel.GetAccountName(String realm)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   em System.Threading.Tasks.Task.Execute()
[10-01-2020 6:26] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/login', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (503) Servidor Não Disponível.
[10-01-2020 6:26] Failed to build HTTP request and get response for: method=GET, url='https://www.pathofexile.com/character-window/get-account-name?realm=pc', allowAutoRedirects=, requestData='': O servidor remoto retornou um erro: (401) Não Autorizado.
[10-01-2020 6:26] Error downloading account name, exception details: System.Net.WebException: O servidor remoto retornou um erro: (401) Não Autorizado.
   em System.Net.HttpWebRequest.GetResponse()
   em POEApi.Transport.HttpTransport.BuildHttpRequestAndGetResponse(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.PerformHttpRequest(HttpMethod method, String url, Nullable`1 allowAutoRedirects, String requestData)
   em POEApi.Transport.HttpTransport.GetAccountName(String realm)
   em POEApi.Model.POEModel.GetAccountName(String realm)
[10-01-2020 6:26] System.Exception: Error downloading account name, details logged to DebugInfo.log. Please open a ticket at https://github.com/Stickymaddness/Procurement/issues and include your DebugInfo.log
   em POEApi.Model.POEModel.GetAccountName(String realm)
   em Procurement.ViewModel.LoginWindowViewModel.<>c__DisplayClass23_0.<Login>b__0()
   em System.Threading.Tasks.Task.Execute()

**Comment by econcert** [comment] 2020-01-10 09:44
already fix it!

**Comment by thailyn** [comment] 2020-01-10 15:12
The log indicates Procurement encountered a 503 error from GGG's API, which is for a [temporary] issue on GGG's end.

Please close this bug now that the issue is resolved.  Thanks!

**Closed** 2020-01-27 15:59 UTC
